/** @jest-environment node */

import fs from "fs";
import os from "os";
import path from "path";
import { Event, Filter, matchFilter } from "nostr-tools";
import {
  pullSyncWorkspace,
  SyncPullProfile,
  SyncQueryClient,
} from "./syncPull";

const ALICE = "a".repeat(64) as PublicKey;
const BOB = "b".repeat(64) as PublicKey;
const RELAY = "wss://profile.example/";
const ONE_DAY_SECONDS = 24 * 60 * 60;
const LOOKBACK_SECONDS = 7 * ONE_DAY_SECONDS;
const FIRST_ALICE_CREATED_AT = 1_700_000_000;
const FIRST_BOB_CREATED_AT = FIRST_ALICE_CREATED_AT + ONE_DAY_SECONDS;

function documentEvent({
  pubkey,
  rootUuid,
  text,
  createdAt,
}: {
  pubkey: PublicKey;
  rootUuid: string;
  text: string;
  createdAt: number;
}): Event {
  return {
    id: `${pubkey.slice(0, 8)}-${rootUuid}-${createdAt}`.padEnd(64, "0"),
    pubkey,
    created_at: createdAt,
    kind: 34770,
    sig: "0".repeat(128),
    tags: [
      ["d", rootUuid],
      ["ms", `${createdAt * 1000}`],
    ],
    content: `# ${text} {${rootUuid}}\n- ${text} child {${rootUuid}-child}\n`,
  };
}

function contactListEvent(): Event {
  return {
    id: "contact-list".padEnd(64, "0"),
    pubkey: ALICE,
    created_at: 10,
    kind: 3,
    sig: "1".repeat(128),
    tags: [["p", BOB]],
    content: "",
  };
}

function makeClient(eventsByRelay: Record<string, Event[]>): {
  client: SyncQueryClient;
  calls: Array<{ relays: string[]; filter: Filter }>;
} {
  const querySync = jest.fn(
    (relays: string[], filter: Filter): Promise<Event[]> => {
      const events = relays.flatMap((relay) => eventsByRelay[relay] || []);
      return Promise.resolve(
        events.filter((event) => matchFilter(filter, event))
      );
    }
  );
  return {
    get calls() {
      return querySync.mock.calls.map(([relays, filter]) => ({
        relays: relays as string[],
        filter: filter as Filter,
      }));
    },
    client: {
      querySync,
      close() {
        return undefined;
      },
    },
  };
}

test("pullSyncWorkspace uses configured relays only and writes raw markdown documents into DOCUMENTS", async () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "knowstr-sync-"));
  const aliceDoc = documentEvent({
    pubkey: ALICE,
    rootUuid: "alice-root",
    text: "Alice Root",
    createdAt: FIRST_ALICE_CREATED_AT,
  });
  const bobDoc = documentEvent({
    pubkey: BOB,
    rootUuid: "bob-root",
    text: "Bob Root",
    createdAt: FIRST_BOB_CREATED_AT,
  });
  const { client, calls } = makeClient({
    [RELAY]: [contactListEvent(), aliceDoc, bobDoc],
  });
  const profile: SyncPullProfile = {
    pubkey: ALICE,
    workspaceDir: tempDir,
    bootstrapRelays: [],
    relays: [{ url: RELAY, read: true, write: true }],
  };

  const manifest = await pullSyncWorkspace(client, profile, {
    now: new Date("2026-03-10T12:00:00.000Z"),
  });

  expect(manifest.relay_urls).toEqual([RELAY]);
  expect(manifest.contact_pubkeys).toEqual([BOB]);
  expect(manifest.authors).toEqual([
    { pubkey: ALICE, last_document_created_at: FIRST_ALICE_CREATED_AT },
    { pubkey: BOB, last_document_created_at: FIRST_BOB_CREATED_AT },
  ]);
  expect(manifest.documents).toHaveLength(2);
  expect(
    calls.every(({ relays }) => relays.every((relay) => relay === RELAY))
  ).toBe(true);

  const alicePath = path.join(
    tempDir,
    manifest.documents.find((document) => document.author === ALICE)?.path || ""
  );
  const bobPath = path.join(
    tempDir,
    manifest.documents.find((document) => document.author === BOB)?.path || ""
  );

  expect(fs.readFileSync(alicePath, "utf8")).toBe(aliceDoc.content);
  expect(fs.readFileSync(bobPath, "utf8")).toBe(bobDoc.content);
  expect(alicePath).toContain(`${path.sep}DOCUMENTS${path.sep}`);
  expect(bobPath).toContain(`${path.sep}DOCUMENTS${path.sep}`);
  const agentsInstructions = fs.readFileSync(
    path.join(tempDir, "AGENTS.md"),
    "utf8"
  );
  expect(agentsInstructions).toContain("generated by `knowstr pull`");
  expect(agentsInstructions).toContain(
    "do not generate UUIDs manually with `uuidgen` or similar tools"
  );
  expect(agentsInstructions).toContain(
    'run `knowstr write create-root --title "<title>"`'
  );
  expect(agentsInstructions).toContain(
    "queue a full markdown document from stdin as a new standalone root"
  );
  expect(agentsInstructions).toContain(
    "pipe the markdown into `knowstr write create-root --stdin`"
  );
  expect(agentsInstructions).toContain(
    "knowstr inspect children --parent <relation-id>"
  );
  expect(agentsInstructions).toContain(
    "knowstr write move-item --from-parent <relation-id> --item <item-id> --to-parent <relation-id>"
  );
  expect(agentsInstructions).toContain("knowstr push");
  expect(agentsInstructions).toContain(
    "update this local workspace immediately and queue signed events locally"
  );
});

test("pullSyncWorkspace refetches documents from a 7 day buffer", async () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "knowstr-sync-"));
  const aliceDoc = documentEvent({
    pubkey: ALICE,
    rootUuid: "alice-root",
    text: "Alice Root",
    createdAt: FIRST_ALICE_CREATED_AT,
  });
  const bobDocV1 = documentEvent({
    pubkey: BOB,
    rootUuid: "bob-root",
    text: "Bob Root",
    createdAt: FIRST_BOB_CREATED_AT,
  });
  const firstClient = makeClient({
    [RELAY]: [contactListEvent(), aliceDoc, bobDocV1],
  });
  const profile: SyncPullProfile = {
    pubkey: ALICE,
    workspaceDir: tempDir,
    bootstrapRelays: [],
    relays: [{ url: RELAY, read: true, write: true }],
  };

  await pullSyncWorkspace(firstClient.client, profile, {
    now: new Date("2026-03-10T12:00:00.000Z"),
  });

  const bobDocV2 = documentEvent({
    pubkey: BOB,
    rootUuid: "bob-root",
    text: "Bob Root Updated",
    createdAt: FIRST_BOB_CREATED_AT + LOOKBACK_SECONDS + ONE_DAY_SECONDS,
  });
  const secondClient = makeClient({
    [RELAY]: [contactListEvent(), aliceDoc, bobDocV1, bobDocV2],
  });

  const manifest = await pullSyncWorkspace(secondClient.client, profile, {
    now: new Date("2026-03-10T13:00:00.000Z"),
  });

  const aliceDocQuery = secondClient.calls.find(
    ({ filter }) =>
      filter.kinds?.includes(34770) && filter.authors?.includes(ALICE)
  );
  const bobDocQuery = secondClient.calls.find(
    ({ filter }) =>
      filter.kinds?.includes(34770) && filter.authors?.includes(BOB)
  );

  expect(aliceDocQuery?.filter.since).toBe(
    FIRST_ALICE_CREATED_AT - LOOKBACK_SECONDS
  );
  expect(bobDocQuery?.filter.since).toBe(
    FIRST_BOB_CREATED_AT - LOOKBACK_SECONDS
  );
  expect(manifest.authors).toEqual([
    { pubkey: ALICE, last_document_created_at: FIRST_ALICE_CREATED_AT },
    {
      pubkey: BOB,
      last_document_created_at:
        FIRST_BOB_CREATED_AT + LOOKBACK_SECONDS + ONE_DAY_SECONDS,
    },
  ]);

  const bobPath = path.join(
    tempDir,
    manifest.documents.find((document) => document.author === BOB)?.path || ""
  );
  expect(fs.readFileSync(bobPath, "utf8")).toBe(bobDocV2.content);
});

test("pullSyncWorkspace reapplies pending local writes after syncing", async () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "knowstr-sync-"));
  const knowstrHome = path.join(tempDir, ".knowstr");
  fs.mkdirSync(knowstrHome, { recursive: true });
  const pendingDoc = documentEvent({
    pubkey: ALICE,
    rootUuid: "pending-root",
    text: "Pending Local Root",
    createdAt: FIRST_ALICE_CREATED_AT + 123,
  });
  fs.writeFileSync(
    path.join(knowstrHome, "pending-writes.json"),
    JSON.stringify(
      {
        entries: [{ event: pendingDoc }],
      },
      null,
      2
    )
  );

  const { client } = makeClient({
    [RELAY]: [contactListEvent()],
  });
  const profile: SyncPullProfile = {
    pubkey: ALICE,
    workspaceDir: tempDir,
    bootstrapRelays: [],
    relays: [{ url: RELAY, read: true, write: true }],
    knowstrHome,
  };

  const manifest = await pullSyncWorkspace(client, profile, {
    now: new Date("2026-03-10T12:00:00.000Z"),
  });

  expect(manifest.documents).toHaveLength(1);
  expect(manifest.documents[0]?.d_tag).toBe("pending-root");
  const pendingPath = path.join(tempDir, manifest.documents[0]?.path || "");
  expect(fs.readFileSync(pendingPath, "utf8")).toBe(pendingDoc.content);
});
