import fs from "fs/promises";
import path from "path";
import { Event } from "nostr-tools";
import { findTag, getEventMs } from "../nostrEvents";
import {
  KIND_DELETE,
  KIND_KNOWLEDGE_DOCUMENT,
  getReplaceableKey,
} from "../nostr";

export const WORKSPACE_VERSION = 1;
export const DOCUMENTS_DIR = "DOCUMENTS";

export type WorkspaceAuthor = {
  pubkey: PublicKey;
  last_document_created_at: number;
};

export type WorkspaceDocument = {
  replaceable_key: string;
  author: PublicKey;
  event_id: string;
  d_tag: string;
  path: string;
  created_at: number;
  updated_ms: number;
};

export type WorkspaceManifest = {
  workspace_version: number;
  as_user: PublicKey;
  synced_at: string;
  relay_urls: string[];
  contact_pubkeys: PublicKey[];
  authors: WorkspaceAuthor[];
  documents: WorkspaceDocument[];
};

function slugify(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "document";
}

function getDocumentTitle(content: string): string {
  const heading = content
    .split("\n")
    .find((line) => line.startsWith("# "))
    ?.replace(/^#\s+/, "")
    .replace(/\s+\{.*\}\s*$/, "")
    .trim();
  return heading || "document";
}

function relativeToWorkspace(workspaceDir: string, targetPath: string): string {
  return path.relative(workspaceDir, targetPath).split(path.sep).join("/");
}

export function manifestPath(workspaceDir: string): string {
  return path.join(workspaceDir, "manifest.json");
}

function workspaceAgentsPath(workspaceDir: string): string {
  return path.join(workspaceDir, "AGENTS.md");
}

export async function loadWorkspaceManifest(
  workspaceDir: string
): Promise<WorkspaceManifest | undefined> {
  try {
    const raw = await fs.readFile(manifestPath(workspaceDir), "utf8");
    return JSON.parse(raw) as WorkspaceManifest;
  } catch {
    return undefined;
  }
}

export async function writeWorkspaceManifest(
  workspaceDir: string,
  manifest: WorkspaceManifest
): Promise<void> {
  await fs.writeFile(
    manifestPath(workspaceDir),
    JSON.stringify(manifest, null, 2),
    "utf8"
  );
}

export function createEmptyWorkspaceManifest(
  asUser: PublicKey
): WorkspaceManifest {
  return {
    workspace_version: WORKSPACE_VERSION,
    as_user: asUser,
    synced_at: new Date(0).toISOString(),
    relay_urls: [],
    contact_pubkeys: [],
    authors: [],
    documents: [],
  };
}

export async function writeWorkspaceInstructions(
  workspaceDir: string,
  manifest: WorkspaceManifest
): Promise<void> {
  const content = `# Knowstr Synced Workspace

This directory is generated by \`knowstr pull\`. It is a local read snapshot of a Knowstr graph.

## What This Directory Is For

- answer questions by reading the synced markdown files
- inspect the latest relay sync state in \`manifest.json\`
- search the workspace with normal file tools such as \`rg\`

## Important Rules

- treat this workspace as generated read-only content except through \`knowstr write\` and \`knowstr push\`
- do not edit files under \`${DOCUMENTS_DIR}/\` directly
- do not create or edit Knowstr markdown files by hand
- do not generate UUIDs manually with \`uuidgen\` or similar tools
- do not edit \`manifest.json\` directly
- for write commands, a bare UUID is treated as your own \`<pubkey>_<uuid>\` ID
- if the user asks for current or latest information, refresh the sync before answering
- your own \`knowstr write\` commands update this local workspace immediately and queue signed events locally
- run \`knowstr push\` to publish queued local events to relays
- rerun \`knowstr pull\` when you need remote changes from relays or other writers

## Available Read And Write Commands

- \`knowstr write create-root --stdin\`: queue a full markdown document from stdin as a new standalone root
- \`knowstr write create-root --file <path>\`: queue a full markdown document from an existing file as a new standalone root
- \`knowstr write create-root --title <text>\`: queue a new standalone root stub with only a heading
- \`knowstr push\`: publish queued local events to relays
- \`knowstr write create-under --parent <relation-id> --stdin\`: insert one markdown subtree under an existing parent relation
- \`knowstr write set-text --relation <relation-id> --text <text>\`: rename or rewrite one existing node without changing its relation ID
- \`knowstr write link --parent <relation-id> --target <relation-id>\`: add a cref under a parent relation
- \`knowstr write set-relevance --parent <relation-id> --item <item-id> --value <contains|relevant|maybe_relevant|little_relevant|not_relevant>\`: update edge relevance
- \`knowstr write set-argument --parent <relation-id> --item <item-id> --value <none|confirms|contra>\`: update edge argument
- \`knowstr write move-item --from-parent <relation-id> --item <item-id> --to-parent <relation-id>\`: move an item while preserving its identity
- \`knowstr write delete-item --parent <relation-id> --item <item-id>\`: delete an item from a parent; owned subtrees are deleted
- use \`--stdin\` when the agent is generating markdown content directly
- use \`--file\` when the markdown already exists on disk
- use \`--title\` only when the user wants an empty/new root started
- if the user explicitly wants the published markdown back, add \`--include-markdown\`
- for markdown uploads, the command uses the same file-wrapping rules as the current uploader
- stdin markdown must resolve to exactly one top-level root or the command will fail
- do not invent other write commands that do not exist yet

## Where To Look

- \`manifest.json\`: sync metadata, authors, contacts, and document file paths
- \`${DOCUMENTS_DIR}/<author>/\`: raw markdown document events grouped by author

## Freshness

Current sync time: \`${manifest.synced_at}\`

If freshness matters, run \`knowstr pull\` again from the agent directory that contains \`.knowstr/profile.json\`.

## Workflow

To answer questions:
- inspect \`manifest.json\`
- search \`${DOCUMENTS_DIR}/\` with \`rg\`

To create a new root:
- run \`knowstr write create-root --title "<title>"\`
- read the refreshed files from \`${DOCUMENTS_DIR}/\`
- run \`knowstr push\` when you want the queued root published to relays

To create a new root from markdown:
- pipe the markdown into \`knowstr write create-root --stdin\`
- read the refreshed files from \`${DOCUMENTS_DIR}/\`
- run \`knowstr push\` when you want the queued root published to relays

To edit an existing relation:
- use relation-aware commands such as \`set-text\`, \`create-under\`, \`link\`, \`set-relevance\`, \`set-argument\`, \`move-item\`, or \`delete-item\`
- read the updated files from \`${DOCUMENTS_DIR}/\`
- run \`knowstr push\` to publish your queued local changes
- rerun \`knowstr pull\` if you need relay freshness from others

Limitations:
- stdin markdown for \`create-root\` and \`create-under\` must have exactly one top-level root
`;
  await fs.writeFile(workspaceAgentsPath(workspaceDir), content, "utf8");
}

function toDocumentFilePath(
  workspaceDir: string,
  author: PublicKey,
  dTag: string,
  content: string
): string {
  const safeDTag = slugify(dTag || "document");
  const titleSlug = slugify(getDocumentTitle(content));
  return path.join(
    workspaceDir,
    DOCUMENTS_DIR,
    author,
    `${safeDTag}-${titleSlug}.md`
  );
}

export async function removeWorkspaceFileIfExists(
  filePath: string
): Promise<void> {
  try {
    await fs.rm(filePath, { force: true });
  } catch {
    // ignore cleanup errors
  }
}

async function writeDocumentFile(
  workspaceDir: string,
  event: Event
): Promise<WorkspaceDocument | undefined> {
  const replaceableKey = getReplaceableKey(event);
  const dTag = findTag(event, "d");
  if (!replaceableKey || !dTag) {
    return undefined;
  }

  const filePath = toDocumentFilePath(
    workspaceDir,
    event.pubkey as PublicKey,
    dTag,
    event.content
  );
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, event.content, "utf8");

  return {
    replaceable_key: replaceableKey,
    author: event.pubkey as PublicKey,
    event_id: event.id,
    d_tag: dTag,
    path: relativeToWorkspace(workspaceDir, filePath),
    created_at: event.created_at,
    updated_ms: getEventMs(event),
  };
}

export function documentMap(
  manifest: WorkspaceManifest | undefined
): Map<string, WorkspaceDocument> {
  return new Map(
    (manifest?.documents || []).map((document) => [
      document.replaceable_key,
      document,
    ])
  );
}

export function authorMap(
  manifest: WorkspaceManifest | undefined
): Map<PublicKey, WorkspaceAuthor> {
  return new Map(
    (manifest?.authors || []).map((author) => [author.pubkey, author])
  );
}

export async function applyDeleteEventsToWorkspaceDocuments(
  workspaceDir: string,
  documents: Map<string, WorkspaceDocument>,
  deleteEvents: Event[]
): Promise<void> {
  await deleteEvents.reduce(async (previous, event) => {
    await previous;
    const replaceableKey = findTag(event, "a");
    const existing = replaceableKey ? documents.get(replaceableKey) : undefined;
    if (
      !replaceableKey ||
      !existing ||
      getEventMs(event) <= existing.updated_ms
    ) {
      return;
    }

    await removeWorkspaceFileIfExists(path.join(workspaceDir, existing.path));
    documents.delete(replaceableKey);
  }, Promise.resolve());
}

export async function applyDocumentEventsToWorkspaceDocuments(
  workspaceDir: string,
  documents: Map<string, WorkspaceDocument>,
  documentEvents: Event[]
): Promise<void> {
  const sortedEvents = [...documentEvents].sort((a, b) => {
    const diff = getEventMs(a) - getEventMs(b);
    return diff !== 0 ? diff : a.id.localeCompare(b.id);
  });

  await sortedEvents.reduce(async (previous, event) => {
    await previous;
    const replaceableKey = getReplaceableKey(event);
    if (!replaceableKey) {
      return;
    }

    const existing = documents.get(replaceableKey);
    if (existing?.event_id === event.id) {
      return;
    }

    const nextDocument = await writeDocumentFile(workspaceDir, event);
    if (!nextDocument) {
      return;
    }

    if (existing && existing.path !== nextDocument.path) {
      await removeWorkspaceFileIfExists(path.join(workspaceDir, existing.path));
    }
    documents.set(replaceableKey, nextDocument);
  }, Promise.resolve());
}

export function updateAuthorsFromKnowledgeDocumentEvents(
  previousAuthors: Map<PublicKey, WorkspaceAuthor>,
  documentEvents: Event[]
): WorkspaceAuthor[] {
  const authors = new Set<PublicKey>(previousAuthors.keys());
  documentEvents.forEach((event) => {
    authors.add(event.pubkey as PublicKey);
  });

  return [...authors].sort().map((pubkey) => {
    const previous = previousAuthors.get(pubkey);
    const latestCreatedAt = documentEvents
      .filter((event) => event.pubkey === pubkey)
      .reduce(
        (current, event) => Math.max(current, event.created_at),
        previous?.last_document_created_at || 0
      );
    return {
      pubkey,
      last_document_created_at: latestCreatedAt,
    };
  });
}

export async function applyKnowledgeEventsToWorkspace(
  workspaceDir: string,
  baseManifest: WorkspaceManifest,
  events: Event[]
): Promise<WorkspaceManifest> {
  await fs.mkdir(path.join(workspaceDir, DOCUMENTS_DIR), { recursive: true });
  const documents = documentMap(baseManifest);
  const documentEvents = events.filter(
    (event) => event.kind === KIND_KNOWLEDGE_DOCUMENT
  );
  const deleteEvents = events.filter((event) => event.kind === KIND_DELETE);

  await applyDeleteEventsToWorkspaceDocuments(
    workspaceDir,
    documents,
    deleteEvents
  );
  await applyDocumentEventsToWorkspaceDocuments(
    workspaceDir,
    documents,
    documentEvents
  );

  const nextManifest: WorkspaceManifest = {
    ...baseManifest,
    documents: [...documents.values()].sort((a, b) =>
      a.path.localeCompare(b.path)
    ),
    authors: updateAuthorsFromKnowledgeDocumentEvents(
      authorMap(baseManifest),
      documentEvents
    ),
  };

  await writeWorkspaceManifest(workspaceDir, nextManifest);
  await writeWorkspaceInstructions(workspaceDir, nextManifest);
  return nextManifest;
}

export async function loadOrCreateWorkspaceManifest(
  workspaceDir: string,
  asUser: PublicKey
): Promise<WorkspaceManifest> {
  return (
    (await loadWorkspaceManifest(workspaceDir)) ||
    createEmptyWorkspaceManifest(asUser)
  );
}
